Fix Alpine's LOGS_STDOUT functionality
Currently, if you try and use `DD_LOGS_STDOUT` with the alpine image you get the following error from the entrypoint script:

```
Error: The directory named as part of the path /dev/stdoutnstdout_logfile_maxbytes=0nstderr_logfile=/dev/stderrnstderr_logfile_maxbytes=0 does not exist. in section ‘program:forwarder’ (file: ‘agent/supervisor.conf’)
```

This is caused by the newlines not being properly interpreted by busybox's `sed` implementation.